<?php

/**
* @file
* Main SDSUdora module file.
* @author Diego Pino Navarro
*/

// Permissions.
define('SDSUDORA_ADMIN', 'Administer sdsudora');

/**
* Implements hook_menu().
*/
function sdsudora_menu() {
  return array(
    'admin/islandora/tools/sdsudora' => array(
      'title' => 'SDSUdora settings',
      'description' => 'Configure SDSUdora-the-explorer.',
      'type' => MENU_NORMAL_ITEM,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('sdsudora_admin_form'),
      'file' => 'includes/admin.form.inc',
      'access arguments' => array(SDSUDORA_ADMIN),
    ),
  );
}

/**
* Implements hook_permission().
*/
function sdsudora_permission() {
  return array(
    SDSUDORA_ADMIN => array(
      'title' => t('Administer SDSUdora'),
      'description' => t('Administer settings for the SDSUdora module.'),
    ),
  );
}



/**
 * Alters breadcrumbs used on Solr search results and within Islandora views.
 *
 * @param array $breadcrumbs
 *   Breadcrumbs array to be altered by reference. Each element is markup.
 * @param string $context
 *   Where the alter is originating from for distinguishing.
 * @param AbstractObject $object
 *   (Optional) AbstractObject representing object providing breadcrumb path
 */
function sdsudora_islandora_breadcrumbs_alter(&$breadcrumbs, $context, $object = NULL) {
  dpm($context);
  if ($context == 'islandora') {
    $values = variable_get('sdsudora_settings', array());
    if (count($values) && isset ($values['sdsudora_settings']['map'])) {
      $i=0;
      dpm($breadcrumbs);
      foreach($values['sdsudora_settings']['map'] as $key => $value) {
      
      $i++; 
      }
    }
    
  }
}  